import type { MetroTheme } from "@/lib/theme";

export const neonTheme: MetroTheme = {
  name: "neon",
  background: "#050014",
  backdrop: "#050014",
  foreground: "#E8F7FF",
  chrome: "#0B0223",
  accent: "#39FF14",
  neutral: "#1F1047",
  fontFamily: '"Orbitron", "Rajdhani", "Segoe UI", sans-serif',
  headingFontFamily: '"Rajdhani", "Orbitron", "Segoe UI", sans-serif',
  tilePalette: {
    lms: "#39FF14",
    profile: "#0FF0FC",
    experience: "#FF3131",
    stack: "#F3F315",
    talk: "#9C1FFF",
    testimonials: "#FF6EC7",
    contact: "#00F5D4",
    github: "#F72585",
    linkedin: "#7209B7",
    sandbox: "#4CC9F0",
  },
  tileContrasts: {
    lms: "dark",
    profile: "dark",
    experience: "dark",
    stack: "dark",
    talk: "light",
    testimonials: "dark",
    contact: "dark",
    github: "dark",
    linkedin: "light",
    sandbox: "dark",
  },
  tileLightText: "#E8F7FF",
  tileDarkText: "#050014",
  tileIcons: {
    lms: "case-study-neon",
    profile: "profile-neon",
    experience: "experience-neon",
    stack: "stack-neon",
    talk: "talk-neon",
    testimonials: "testimonials-neon",
    contact: "contact-neon",
    github: "github-neon",
    linkedin: "linkedin-neon",
    sandbox: "sandbox-neon",
  },
};
