import type { MetroTheme } from "@/lib/theme";

export const orchidTheme: MetroTheme = {
  name: "orchid",
  background: "#1E023D",
  backdrop: "#1E023D",
  foreground: "#FFF7FB",
  chrome: "rgba(59, 2, 112, 0.85)",
  accent: "#FFD866",
  neutral: "rgba(230, 182, 255, 0.32)",
  fontFamily: '"Raleway", "Segoe UI", "Helvetica Neue", Arial, sans-serif',
  headingFontFamily: '"Playfair Display", "Raleway", "Segoe UI", serif',
  tilePalette: {
    lms: "#6F00FF",
    profile: "#3B0270",
    experience: "#FFD45C",
    stack: "#FFE7A8",
    talk: "#9045F5",
    testimonials: "#F7B3FF",
    contact: "#FF9CD5",
    github: "#DDB8FF",
    linkedin: "#F3D2FF",
    sandbox: "#FFF5CC",
  },
  tileContrasts: {
    lms: "light",
    profile: "light",
    experience: "dark",
    stack: "dark",
    talk: "light",
    testimonials: "dark",
    contact: "dark",
    github: "dark",
    linkedin: "dark",
    sandbox: "dark",
  },
  tileLightText: "#FFF9FE",
  tileDarkText: "#25043F",
  tileIcons: {
    lms: "case-study-orchid",
    profile: "profile-orchid",
    experience: "experience-orchid",
    stack: "stack-orchid",
    talk: "talk-orchid",
    testimonials: "testimonials-orchid",
    contact: "contact-orchid",
    github: "github-orchid",
    linkedin: "linkedin-orchid",
    sandbox: "sandbox-orchid",
  },
};
