import type { MetroTheme } from "@/lib/theme";

export const solarTheme: MetroTheme = {
  name: "solar",
  background: "#120800",
  backdrop: "#120800",
  foreground: "#FFF6E6",
  chrome: "#241200",
  accent: "#FFB200",
  neutral: "#3C1F00",
  fontFamily: '"Montserrat", "Poppins", "Segoe UI", sans-serif',
  headingFontFamily: '"Poppins", "Montserrat", "Segoe UI", sans-serif',
  tilePalette: {
    lms: "#FFC300",
    profile: "#FF7D00",
    experience: "#FF5400",
    stack: "#FFBD69",
    talk: "#FF8A5C",
    testimonials: "#FFE156",
    contact: "#FF5C8A",
    github: "#FFAFCC",
    linkedin: "#FFD6A5",
    sandbox: "#FFBE7B",
  },
  tileContrasts: {
    lms: "dark",
    profile: "dark",
    experience: "dark",
    stack: "dark",
    talk: "dark",
    testimonials: "dark",
    contact: "dark",
    github: "dark",
    linkedin: "dark",
    sandbox: "dark",
  },
  tileLightText: "#FFF6E6",
  tileDarkText: "#140A00",
  tileIcons: {
    lms: "case-study-solar",
    profile: "profile-solar",
    experience: "experience-solar",
    stack: "stack-solar",
    talk: "talk-solar",
    testimonials: "testimonials-solar",
    contact: "contact-solar",
    github: "github-solar",
    linkedin: "linkedin-solar",
    sandbox: "sandbox-solar",
  },
};
